
services:
  server_api:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Api/Dockerfile
    ports:
      - 1488:8080
    depends_on: 
      - server_core

  server_core:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Server/Dockerfile
  server_telegram:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Telegram/Dockerfile
    depends_on: 
      - server_core

  database_redis:
    image: redis

  database_pg:
    volumes:
     - postgres:/data/postgres
    image: postgres


volumes:
  postgres:
