
services:
  server_api:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Api/Dockerfile
    ports:
      - 1111:8080
    depends_on: 
      - server_core

  server_core:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Server/Dockerfile
    environment:
      - RUNNING_IN_CONTAINER=1
    ports:
      - 1488:8080

  server_telegram:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Telegram/Dockerfile
    depends_on: 
      - server_core

  database_redis:
    image: redis

  database_pg:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - postgres:/data/postgres
    image: postgres


volumes:
  postgres:
