
services:
  server_api:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Api/Dockerfile.dev
    command: dotnet watch
    develop:
      watch:
        - action: sync
          path: ./src/Server/Hako.Api
          target: /source/
    ports:
      - 1488:8080
    depends_on: 
      - server_core

  server_core:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Server/Dockerfile.dev
    command: dotnet watch
    environment:
      - RUNNING_IN_CONTAINER=1
    ports:
      - 1488:8080
    develop:
      watch:
        - action: sync
          path: ./src/Server/Hako.Server
          target: /source/

  server_telegram:
    build:
      context: ./src/
      dockerfile: ./Server/Hako.Telegram/Dockerfile.dev
    command: dotnet watch
    develop:
      watch:
        - action: sync
          path: ./src/Server/Hako.Telegram
          target: /source/
    depends_on: 
      - server_core

  database_redis:
    image: redis

  database_pg:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - postgres:/data/postgres
    image: postgres

volumes:
  postgres:
